sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tmakgalo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tmakgalo/docker-react-react npm run test -- --coverage
